import marshmallow as m


class Insertcampdata(m.Schema):
    message = m.fields.Str(missing=None)
    name = m.fields.Str(missing=None)
    email = m.fields.Email(required=True)
    phone = m.fields.Integer(missing=0)
    type = m.fields.Str(missing=None)
    sidingColor = m.fields.Str(missing=None)
    sidingColorPrice = m.fields.Decimal(missing=0)
    stripeColor = m.fields.Str(missing=None)
    stripeColorPrice = m.fields.Decimal(missing=0)
    length = m.fields.Integer(missing=0)
    width = m.fields.Integer(missing=0)
    height = m.fields.Integer(missing=0)
    spline = m.fields.Integer(missing=0)
    areaPrice = m.fields.Decimal(missing=0)
    roofStyle = m.fields.Str(missing=None)
    roofStylePrice = m.fields.Decimal(missing=0)
    thickness = m.fields.Str(missing=None)
    thicknessPrice = m.fields.Decimal(missing=0)
    frontWindOne = m.fields.Str(missing=None)
    frontWindOnePrice = m.fields.Decimal(missing=0)
    frontWindTwo = m.fields.Str(missing=None)
    frontWindTwoPrice = m.fields.Decimal(missing=0)
    frontWindThree = m.fields.Str(missing=None)
    frontWindThreePrice = m.fields.Decimal(missing=0)
    frontDoor = m.fields.Str(missing=None)
    frontDoorPrice = m.fields.Decimal(missing=0)
    backWindOne = m.fields.Str(missing=None)
    backWindOnePrice = m.fields.Decimal(missing=0)
    backWindTwo = m.fields.Str(missing=None)
    backWindTwoPrice = m.fields.Decimal(missing=0)
    backWindThree = m.fields.Str(missing=None)
    backWindThreePrice = m.fields.Decimal(missing=0)
    backDoor = m.fields.Str(missing=None)
    backDoorPrice = m.fields.Decimal(missing=0)
    leftWindOne = m.fields.Str(missing=None)
    leftWindOnePrice = m.fields.Decimal(missing=0)
    leftWindTwo = m.fields.Str(missing=None)
    leftWindTwoPrice = m.fields.Decimal(missing=0)
    leftWindThree = m.fields.Str(missing=None)
    leftWindThreePrice = m.fields.Decimal(missing=0)
    leftDoor = m.fields.Str(missing=None)
    leftDoorPrice = m.fields.Decimal(missing=0)
    rightWindOne = m.fields.Str(missing=None)
    rightWindOnePrice = m.fields.Decimal(missing=0)
    rightWindTwo = m.fields.Str(missing=None)
    rightWindTwoPrice = m.fields.Decimal(missing=0)
    rightWindThree = m.fields.Str(missing=None)
    rightWindThreePrice = m.fields.Decimal(missing=0)
    rightDoor = m.fields.Str(missing=None)
    rightDoorPrice = m.fields.Decimal(missing=0)
    tprice = m.fields.Decimal(missing=0)
    d_image_1 = m.fields.Str(missing=None)
    d_image_2 = m.fields.Str(missing=None)
    d_image_3 = m.fields.Str(missing=None)
    d_image_4 = m.fields.Str(missing=None)
    status = m.fields.Str(missing='pending')



    class Meta:
        unknown = m.EXCLUDE
